# ?????
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/resume_rag?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
db.username=root
db.password=Zal13715002181,

# ?????
db.maximumPoolSize=10
db.connectionTimeout=30000
db.idleTimeout=600000
db.maxLifetime=1800000