# Database configuration
db.url=jdbc:mysql://localhost:3306/resume_rag?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
db.user=root
db.password=Zal13715002181,
